"""正式协议中已确认的目标航迹常量。"""

TRACK_FRAME_HEADER = 0xA3A3AAAA
TRACK_FRAME_TAIL = 0xAAAA3A3A
FIXED_HEADER_WORDS = 20
TRACK_WORDS = 16
TRAILER_WORDS = 2
MIN_FRAME_WORDS = FIXED_HEADER_WORDS + TRAILER_WORDS
MAX_TRACK_COUNT = 500
COORDINATE_SCALE_DEG = 0.00001
